version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ohdm-frontend
    volumes:
      - ./react:/home/node/app
    ports:
        - 80:3000
